version: "3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4584:4566-4584"
    environment:
      - SERVICES=sqs,events
      - DEBUG=1
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook